ft-image-uploading
Honore123/MyBrand pull request #12
Opened 2023-03-20 19:16 UTC by Honore123

#### What does this PR do?
It allows administrator to upload thumbnail
#### Description of Task to be completed
Installed multer and created a middleware for uploading images
#### How should this be manually tested?
You can visit [https://honore123.github.io/MyBrand/admin/login.html](url), then login and create new blog post

2023-03-20 21:10 UTC, sezeranoJchrisostome requested changes
# Well done @Honore123 
I have left comments on things that may improve the code readability.  Please you may check them out,

2023-03-20 21:10 UTC, sezeranoJchrisostome commented on controllers/blogController.js
Instead of having `req.` in different places. would try to restructure 
```javascript
   const { params } = req;
```

2023-03-20 21:10 UTC, sezeranoJchrisostome commented on controllers/blogController.js
You can do this for every places you have object that is repeated the same way as this one

2023-03-21 06:30 UTC, Honore123 commented on controllers/blogController.js
Okay

2023-03-21 07:58 UTC, merged